server.port=8080
server.servlet.context-path=/
server.servlet.session.timeout=30m
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.problemdetails.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
