-- 二阶段评价标签与图片字段幂等升级。
SET @db := DATABASE();
SET @ddl := (SELECT IF(COUNT(*)=0,'ALTER TABLE reviews ADD COLUMN tags JSON NULL','SELECT 1')
 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='reviews' AND COLUMN_NAME='tags');
PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
SET @ddl := (SELECT IF(COUNT(*)=0,'ALTER TABLE reviews ADD COLUMN images JSON NULL','SELECT 1')
 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='reviews' AND COLUMN_NAME='images');
PREPARE s FROM @ddl; EXECUTE s; DEALLOCATE PREPARE s;
